// Home dashboard uchun nom bo'yicha lucide ikonasi.
import {
  ArrowDown,
  ArrowUp,
  CircleHelp,
  CircuitBoard,
  Clock,
  Download,
  ExternalLink,
  FileSpreadsheet,
  FileText,
  FileWarning,
  Gavel,
  HandCoins,
  Phone,
  PlugZap,
  ShieldCheck,
  SquareArrowOutUpRight,
  SquareCheckBig,
  TriangleAlert,
  SquareChartGantt,
  Table2,
  TrendingDown,
  UserMinus,
  Users,
  Zap,
  ZapOff,
  type LucideProps,
} from "lucide-react";

const MAP = {
  ArrowDown,
  ArrowUp,
  CircuitBoard,
  Clock,
  Download,
  ExternalLink,
  FileSpreadsheet,
  FileText,
  FileWarning,
  Gavel,
  HandCoins,
  Phone,
  PlugZap,
  ShieldCheck,
  SquareArrowOutUpRight,
  SquareAlert: TriangleAlert,
  SquareCheckBig,
  SquareChartGantt,
  Table2,
  TrendingDown,
  UserMinus,
  Users,
  Zap,
  ZapOff,
} as const;

export function Icon({ name, ...props }: { name: string } & LucideProps) {
  const Cmp = (MAP as Record<string, typeof Zap>)[name] ?? CircleHelp;
  return <Cmp {...props} />;
}
